# Generated by Django 5.2.8 on 2025-11-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqr', '0005_pqr_ciudad_pqr_departamento_pqr_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='observacion_tecnico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
